config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboard#index'

  get '/auth/github/callback' => 'sessions#create'
  delete '/sign_out' => 'sessions#destroy', as: :sign_out
  get '/auth/failure' => 'sessions#failure'

  resources :projects, except: :index

end

app/models/buildkite.rb
class Buildkite

  class Client

    PROTOCOL = 'https'
    HOSTNAME = 'api.buildkite.com'
    VERSION  = 'v1'


    def get(path, params={})
      connection.get path, params
    end


    private

      def connection
        @connection ||= Faraday.new(url) do |faraday|
          faraday.request :instrumentation
          faraday.request :authorization, 'Bearer', ENV['BUILDKITE_TOKEN']
          faraday.request :json

          faraday.response :raise_error
          faraday.response :json
          # faraday.response :logger if Rails.env.development?

          faraday.adapter Faraday.default_adapter
        end
      end

      def url
        "#{PROTOCOL}://#{HOSTNAME}/#{VERSION}"
      end

  end


  def self.organization
    Organization.new
  end

  def self.projects
    Projects.new
  end

end

app/models/buildkite/artifact.rb
class Buildkite::Artifact < Buildkite::Resource

  def initialize(project_slug, build_number)
    @project_slug = project_slug
    @build_number = build_number
  end

  def path
    "organizations/#{ENV['BUILDKITE_ORG_NAME']}/projects/#{@project_slug}/builds/#{@build_number}/artifacts"
  end

  def to_s
    self[:filename]
  end

  def data
    @data ||= (response.body.first.try(:with_indifferent_access) || nil)
  end

  def nil?
    @data.nil?
  end

end

app/models/buildkite/build.rb
class Buildkite::Build < Buildkite::Resource

  def initialize(project_slug, data_or_id)
    @project_slug = project_slug

    if data_or_id.is_a?(String)
      @slug = data_or_id
    else
      @data = data_or_id.with_indifferent_access
    end
  end

  def artifact
    Buildkite::Artifact.new(@project_slug, self[:number])
  end

  def path
    "organizations/#{ENV['BUILDKITE_ORG_NAME']}/projects/#{@project_slug}/builds/#{slug}"
  end

  def to_s
    self[:message]
  end

end

app/models/buildkite/builds.rb
class Buildkite::Builds < Buildkite::Resources
  attr_reader :project_slug


  def initialize(project_slug=nil, options)
    @options = options
    @project_slug = project_slug
  end

  def each
    response.body.each { |build| yield Buildkite::Build.new(project_slug, build) }
  end

  def params
    @options
  end

  def path
    if project_slug
      "organizations/#{ENV['BUILDKITE_ORG_NAME']}/projects/#{project_slug}/builds"
    else
      "organizations/#{ENV['BUILDKITE_ORG_NAME']}/builds"
    end
  end

end

app/models/buildkite/organization.rb
class Buildkite::Organization < Buildkite::Resource

  attr_reader :org_name


  def initialize
    @org_name = ENV['BUILDKITE_ORG_NAME']
  end

  def path
    "organizations/#{org_name}"
  end

  def projects
    @projects ||= Buildkite.projects
  end

end

app/models/buildkite/project.rb
class Buildkite::Project < Buildkite::Resource

  def initialize(data_or_slug)
    if data_or_slug.is_a?(String)
      @slug = data_or_slug
    else
      @data = data_or_slug.with_indifferent_access
    end
  end

  def builds(*args)
    options = args.extract_options!
    Buildkite::Builds.new(slug, options)
  end

  def path
    "organizations/#{ENV['BUILDKITE_ORG_NAME']}/projects/#{slug}"
  end

  def github_path
    @github_path ||= begin
      if matched = self[:repository].match(/github.com[:\/]([\w\-]+\/[\w\-]+)/i)
        matched[1]
      else
        raise "#{self[:repository]} is not a Github repository."
      end
    end
  end

  def github_url
    "https://githun.com/#{github_path}"
  end

end

app/models/buildkite/projects.rb
class Buildkite::Projects < Buildkite::Resources

  def each
    response.body.each { |project| yield Buildkite::Project.new(project) }
  end

  def path
    "organizations/#{ENV['BUILDKITE_ORG_NAME']}/projects"
  end

end

app/models/buildkite/resource.rb
class Buildkite::Resource
  attr_reader :data, :slug

  def [](key)
    data[key]
  end

  def to_s
    self[:name]
  end

  def to_param
    self[:slug]
  end

  def data
    @data ||= response.body.with_indifferent_access
  end


  private

    def response
      @response ||= client.get(path)
    end

    def path
      ''
    end

    def client
      @client ||= Buildkite::Client.new
    end

end

app/models/buildkite/resources.rb
class Buildkite::Resources
  include Enumerable


  def each
    response.body.each { |item| yield item }
  end


  private

    def response
      @response ||= client.get(path, params)
    end

    def path
      ''
    end

    def params
      {}
    end

    def client
      @client ||= Buildkite::Client.new
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :signed_in?
  helper_method :current_org

  add_breadcrumb 'Dashboard', :root_path


  private

    def current_user
      begin
        @current_user ||= CurrentUser.new(session[:github_auth] || {})
      rescue
        nil
      end
    end

    def signed_in?
      current_user.signed_in?
    end

    def authenticate_user!
      if !signed_in?
        redirect_to root_url, alert: 'You need to sign in for access to this page.'
      end
    end

    def current_org
      @current_org ||= Buildkite.organization
    end

    def github
      @github ||= Octokit::Client.new access_token: session[:github_auth]['token']
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!, except: :index


  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = Buildkite::Project.new(params[:id])
    @pulls = github.pull_requests(@project.github_path, base: 'master')
    branches = @pulls.map { |pull| pull[:head][:ref] } << 'master'
    @builds = @project.builds(state: 'passed', branch: branches)
                      .sort_by { |b| b[:branch] }
                      .group_by { |b| b[:branch] }
  rescue Faraday::ResourceNotFound
    redirect_to :root
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    reset_session
    auth = request.env["omniauth.auth"]

    # Check that this user is a member of the Github organization.
    client = Octokit::Client.new access_token: auth['credentials']['token']
    unless client.org_member?(org_name, client.user.login)
      redirect_to root_url, alert: "Authentication error: you are not a member of the #{org_name}."
    end

    session[:github_auth] = {
      username: client.user.login,
      uid: auth['uid'],
      token: auth['credentials']['token']
    }
    redirect_to root_url, notice: 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Signed out!'
  end

  def failure
    redirect_to root_url, alert: "Authentication error: #{params[:message].humanize}"
  end


  private

    def org_name
      ENV['GITHUB_ORG_NAME']
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title)
    content_for :page_title, title
  end

  def page_title_for_header
    if content_for?(:page_title)
      strip_tags "#{content_for(:page_title)} &ndash; Brick"
    else
      'Brick'
    end
  end

  def flash_type_for(flash_type)
    case flash_type.to_sym
      when :alert
        "negative"
      when :notice
        "positive"
      else
        flash_type.to_s
    end
  end

  def icon(*names)
    options = names.extract_options!
    content_tag :i, nil, options.merge(class: names.map{|name| "#{name.to_s.gsub('_','-')}" } << 'icon')
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboard/index.html.erb
<%- if signed_in? -%>

  <%- if current_org.projects.count > 0 -%>

    <h3 class="ui dividing header">
      <%= current_org %> Projects
    </h3>
    <div class="ui horizontal large very relaxed divided list">
      <%- current_org.projects.each do |project| -%>
        <div class="item">
          <%= icon :large, :aligned, :middle, project[:provider][:id] %>
          <div class="content">
            <div class="right floated content">
              <%= link_to icon(:external, data: { content: 'Open project on Buildkite' }), project[:web_url], target: '_blank' %>
            </div>
            <div class="header"><%= link_to project, project_path(project) %></div>
            <div class="description"><%= project[:repository] %></div>
          </div>
        </div>
      <%- end -%>
    </div>

  <%- else -%>

    <div class="ui icon message">
      <%= icon :info, :circle %>
      <div class="content">
        <div class="header">
          You do not currently have any Buildkite projects.
        </div>
        <p><%= link_to 'Create your first project now', "https://buildkite.com/organizations/#{current_org.to_param}/projects/new", target: '_blank' %>, then come back here and reload this page.</p>
      </div>
    </div>

  <%- end -%>

<%- else -%>

  <div class="alert alert-danger">You are not signed in! <%= link_to 'Sign in via Github...', '/auth/github', class: 'alert-link' %></div>

<%- end -%>

app/views/layouts/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="ui <%= flash_type_for type %> message">
    <i class="close icon"></i>
    <div class="header"><%= message %></div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title><%= page_title_for_header %></title>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <nav class="main">
      <div>

        <%- if signed_in? -%>
          <div id="project-selector">
            <%= link_to icon(:small, :home, :circular, :inverted), root_path %>
            <%= link_to @project, project_path(@project), class: 'current-project-link' if @project %>
            <%- if current_org.projects.count > 0 -%>
              <div>
                <%- if @project -%>
                  <%= link_to icon(:angle, :down, :large), 'javascript:void(0)', class: 'caret' %>
                <%- else -%>
                  <%= link_to raw("Select project #{icon(:angle, :down, :large)}"), 'javascript:void(0)', class: 'caret' %>
                <%- end -%>

                <ul>
                  <%- current_org.projects.each do |project| -%>
                    <li class="<%= @project && @project[:id] == project[:id] && 'active' %>"><%= link_to project, project_path(project) %></li>
                  <%- end -%>
                </ul>
              </div>
            <%- end -%>
          </div>
        <%- else -%>
          <ul id="home-nav">
            <li><%= link_to 'Home', root_path %></li>
          </ul>
        <%- end -%>

        <div id="logo"><%= link_to 'Brick', root_path %></div>

        <ul id="user-nav">
          <%- if signed_in? -%>
            <li>signed in as <%= current_user %></li>
            <li><%= link_to icon(:sign, :out), sign_out_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <%- else -%>
            <li><%= link_to 'Sign in', '/auth/github' %></li>
          <%- end -%>
        </ul>
      </div>
    </nav>

    <header>
      <%= yield :header %>
    </header>

    <main>
      <%= render partial: "layouts/flashes", flash: flash %>
      <%= yield %>
    </main>

    <footer>
      <div>
        <div class="pull right">Contact me at <%= mail_to 'joel@developwithstyle.com' %></div>
        &copy; Joel Moss &ndash; Developed with Style
      </div>
    </footer>

  </body>
</html>

app/views/projects/show.html.erb
<div class="ui vertically divided grid">
  <div class="zero padded row">
    <div class="ten wide column">
      <h1 class="ui header">
        <%= @project %>
        <%= link_to icon(:external, data: { content: 'Open project on Buildkite' }), @project[:web_url], target: '_blank' %>
      </h1>
    </div>
    <div class="right aligned six wide column">
      <h4>
        <%= link_to @project.github_url, target: '_blank' do %>
          <%= icon @project[:provider][:id], :large %>
          <span><%= @project.github_path %></span>
        <%- end -%>
      </h4>
    </div>
  </div>
  <div class="row"></div>
</div>

<div class="center">
  <div class="ui horizontal small statistic">
    <div class="value">
      <%= @pulls.count %>
    </div>
    <div class="label">
      Pull Requests
    </div>
  </div>

  <div class="ui horizontal small statistic">
    <div class="value">
      <%= @project[:scheduled_builds_count] %>
    </div>
    <div class="label">
      Scheduled Builds
    </div>
  </div>

  <div class="ui horizontal small statistic">
    <div class="value">
      <%= @project[:running_builds_count] %>
    </div>
    <div class="label">
      Running Builds
    </div>
  </div>
</div>

<h4 class="ui horizontal divider header">
  Open Pull Requests
  <div class="sub header">Feature branches only (base is master)</div>
</h4>

<div class="ui large very very relaxed divided list">
  <%- @pulls.each do |pull| -%>
    <div class="item">
      <div class="right floated content">
        <%= link_to raw("#{pull[:head][:ref]} #{icon(:fork, :small)}"), pull[:html_url] %>
      </div>
      <%= icon :large, :github, :disabled %>

      <div class="content">
        <div class="header"><%= pull[:title] %></div>

        <%- if @builds[pull[:head][:ref]] && (build = @builds[pull[:head][:ref]].first) -%>
          <div class="description">
            <div class="ui top padded"><%= link_to build, build[:web_url] %></div>
            <small class="ui uppercase">
              <small><code><%= link_to build[:commit], "#{@project.github_url}/commit/#{build[:commit]}" %></code></small>
              <small class="ui left right padded">|</small>
              <small data-content="<%= DateTime.parse(build[:finished_at]).to_s :short %>">
                finished <%= time_ago_in_words DateTime.parse(build[:finished_at]) %> ago
              </small>
              <%- if build.artifact.nil? -%>
                <small class="ui left right padded">|</small>
                <small><i>no artifact!</i></small>
              <%- end -%>
            </small>

            <%- unless build.artifact.nil? -%>
              <div>
                <%= build.artifact %>
              </div>
            <%- end -%>
          </div>
        <%- else -%>
          <small class="description">
            <i>Cannot find any successful builds for this PR and branch</i>
          </small>
        <%- end -%>
      </div>
    </div>
  <%- end -%>
</div>